<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestSuite_DN</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>83d01546-9418-482b-bf29-bbda49f3dffc</testSuiteGuid>
   <testCaseLink>
      <guid>e33e4a52-edd6-4dc3-910c-9c070f0004c1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Test_DangNhap/Test Case_DN</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>9070cd89-db1f-49d0-b2da-2a1f04f75735</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data_DN</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>9070cd89-db1f-49d0-b2da-2a1f04f75735</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>user</value>
         <variableId>0baf9158-bb86-4fdb-90ab-1cf19f9b62e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9070cd89-db1f-49d0-b2da-2a1f04f75735</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>pass</value>
         <variableId>cfcf1ee5-c994-4e06-9c38-2d4c9adf0836</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
